Repository weprovide/valet-plus, pull requests merged in 2020-01, with the labels that each got.

#425 Add PHP 7.4
  azure-pipelines.yml
  cli/Valet/AbstractPecl.php
  cli/Valet/PeclCustom.php
  cli/Valet/PhpFpm.php
  cli/valet.php
Labels: 2.x, Feature request, MINOR

#426 Use 7.2 as default (as per Readme)
  cli/Valet/PhpFpm.php
Labels: 2.x, Bug, Documentation

#408 Always suffix Elasticsearch version in datapath #407
  cli/Valet/Elasticsearch.php
  readme.md
Labels: 2.x, PATCH
