Repository weprovide/valet-plus, pull requests merged in 2020-10, with the labels that each got.

#533 Fix CI/CD not adhering to installation instructions
  azure-pipelines.yml
Labels: 2.x, Bug, PATCH

#535 Deprecate old PHP fixes for old brew formulae
  cli/Valet/PhpFpm.php
  cli/valet.php
Labels: 2.x, Deprecation, PATCH

#537 Fix valet fix forcefully reinstalling and relinking the default PHP version
  azure-pipelines.yml
  cli/Valet/PhpFpm.php
Labels: 2.x, Bug, PATCH

#524 [FIX] Set new default ES version and remove unsupported
  cli/Valet/Elasticsearch.php
Labels: 2.x, MINOR
